### ISSUE TITLE
refactor TickDataProvider Trait to Enum for simplified tick data handling

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [shuhuiluo/uniswap-v3-sdk-rs#43]
Refactor the TickDataProvider trait and its implementations into a single enum. This change aims to streamline tick data handling by encapsulating the various data provider strategies within enum variants

**Comment by shuhuiluo** [comment]
`TickDataProvider` is an interface in the TS SDK which translates naturally to a trait. What's the rationale to make it an enum?

**Comment by DoTheBestToGetTheBest** [comment]
> `TickDataProvider` is an interface in the TS SDK which translates naturally to a trait. What's the rationale to make it an enum?

Basically the traits in Rust we use them to allow the same trait to be implemented for other types and for libraries, it would be more user-friendly it seems to me to use an enum here because we will only need this trait once times. What do you think ?

**Comment by shuhuiluo** [comment]
> > `TickDataProvider` is an interface in the TS SDK which translates naturally to a trait. What's the rationale to make it an enum?
> 
> Basically the traits in Rust we use them to allow the same trait to be implemented for other types and for libraries, it would be more user-friendly it seems to me to use an enum here because we will only need this trait once times. What do you think ?

I would leave it as a trait for authenticity and extensibility.
