### ISSUE TITLE
Migrate from `ethers-rs` to `alloy`

### ISSUE THREAD

**Issue by shuhuiluo** [shuhuiluo/uniswap-v3-sdk-rs#51]
Move all middleware interactions from `ethers-rs` to `alloy`. Blocked by contract bindings.

**Comment by shuhuiluo** [comment]
Now that `forge bind` supports `alloy`, it's time to use `uniswap-lens-rs` instead of `aperture-lens`.

**Comment by malik672** [comment]
@shuhuiluo will pull something nxt wk
