### ISSUE TITLE
Trying to get_pool() but failed for certain tokens

### ISSUE THREAD

**Issue by lamhochit** [shuhuiluo/uniswap-v3-sdk-rs#52]
I am trying to call the get_pool() function for the below tokens, however it encounters a bad data error

Token 0: 0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2
Token 1: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

`let pool = get_pool(1,
                        address!("1F98431c8aD98523631AE4a59f267346ea31F984"),
                        address!("9f8F72aA9304c8B593d555F12eF6589cC3A579A2"),
                        address!("A0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"),
                        FeeAmount::MEDIUM,
                        provider.clone(),
                        None).await?;`

**Comment by shuhuiluo** [comment]
Thanks for reporting this. It's because the [MKR](https://etherscan.io/address/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2#code) token's `name()` and `symbol()` function return `bytes32` instead of `bytes`.

**Comment by lamhochit** [comment]
Thank you!
