### ISSUE TITLE
Suggestion to make fn's in TickDataProvider trait mutable to fetch tick data during calculation

### ISSUE THREAD

**Issue by cakevm** [shuhuiluo/uniswap-v3-sdk-rs#92]
I am working on a library ([rethdb-dexsync](https://github.com/cakevm/rethdb-dexsync)) where I would like to fetch tick data on demand from a Reth node database. However, it seems that the TickDataProvider requires prefetching all tick data during initialization, as the data cannot be modified during the calculation.

Since `&self` is not mutable, I currently don't see a way to dynamically fetch and return a reference to new fetched ticks. Is this a use case you would like to support? Or am I missing something, perhaps there is a deref workaround that I haven't considered?

```rust
pub trait TickDataProvider {
    type Index: TickIndex;
    fn get_tick(&self, tick: Self::Index) -> Result<&Tick<Self::Index>, Error>;
    fn next_initialized_tick_within_one_word(
        &self,
        tick: Self::Index,
        lte: bool,
        tick_spacing: Self::Index,
    ) -> Result<(Self::Index, bool), Error>;
}
```

**Comment by shuhuiluo** [comment]
Are you trying to implement `TickDataProvider` on your own type? Have you tried wrapping your tick data provider in `RefCell`? Making `TickDataProvider` use `&mut self` will likely incur a larger refactor, requiring `Pool` and `Position` to be mutable as well.

I also don't see why reading from Reth requires mutability, unless you cache the result inside `get_tick`.

**Comment by cakevm** [comment]
Exactly, I really like the possibility of bringing my own provider and have tried to do so. And you're right, I want to cache the result in the provider to reuse it for multiple calculations. The problem I'm facing is returning a reference. My current code looks like [this](https://github.com/cakevm/rethdb-dexsync/blob/v3-sdk/examples/univ3_sdk_pool.rs#L21), but the RefCell approach fails to compile, and I get the following error:
```
error[E0515]: cannot return value referencing local variable `ticks_ref`
  --> examples/univ3_sdk_pool.rs:44:24
   |
43 |         match ticks_ref.get(&tick_id) {
   |               --------- `ticks_ref` is borrowed here
44 |             Some(v) => Ok(v),
   |                        ^^^^^ returns a value referencing data owned by the current function
   ```
code: 
```rust
fn get_tick(&self, tick_id: Self::Index) -> Result<&Tick<Self::Index>, Error> {
    ...
    let tick = Tick::new(tick_id, tick_info.liquidity_gross.to(), i128::try_from(tick_info.liquidity_net).unwrap());
    self.ticks.borrow_mut().insert(tick_id, tick);

    let ticks_ref = self.ticks.borrow();
    match ticks_ref.get(&tick_id) {
        Some(v) => Ok(v),
        None => Err(Error::InvalidTick(tick_id)),
    }
}
```

The problem is how I can store somewhere a reference in this function and return it. I got the idea that the return value is of course a reference to not clone the tick every time. But make returning the fn just a `Tick` would also help me to move forward. I don't know if it makes sense somehow to have a get_tick() and get_tick_ref() where the ref function is always evaluated first. I would appreciate any hints or suggestions to resolve this issue.

**Comment by shuhuiluo** [comment]
> Exactly, I really like the possibility of bringing my own provider and have tried to do so. And you're right, I want to cache the result in the provider to reuse it for multiple calculations. The problem I'm facing is returning a reference. My current code looks like [this](https://github.com/cakevm/rethdb-dexsync/blob/v3-sdk/examples/univ3_sdk_pool.rs#L21), but the RefCell approach fails to compile, and I get the following error:
> 
> ```
> error[E0515]: cannot return value referencing local variable `ticks_ref`
>   --> examples/univ3_sdk_pool.rs:44:24
>    |
> 43 |         match ticks_ref.get(&tick_id) {
>    |               --------- `ticks_ref` is borrowed here
> 44 |             Some(v) => Ok(v),
>    |                        ^^^^^ returns a value referencing data owned by the current function
> ```
> 
> code:
> 
> ```rust
> fn get_tick(&self, tick_id: Self::Index) -> Result<&Tick<Self::Index>, Error> {
>     ...
>     let tick = Tick::new(tick_id, tick_info.liquidity_gross.to(), i128::try_from(tick_info.liquidity_net).unwrap());
>     self.ticks.borrow_mut().insert(tick_id, tick);
> 
>     let ticks_ref = self.ticks.borrow();
>     match ticks_ref.get(&tick_id) {
>         Some(v) => Ok(v),
>         None => Err(Error::InvalidTick(tick_id)),
>     }
> }
> ```
> 
> The problem is how I can store somewhere a reference in this function and return it. I got the idea that the return value is of course a reference to not clone the tick every time. But make returning the fn just a `Tick` would also help me to move forward. I don't know if it makes sense somehow to have a get_tick() and get_tick_ref() where the ref function is always evaluated first. I would appreciate any hints or suggestions to resolve this issue.

Try
```rust
        let ticks_ref = unsafe { self.ticks.as_ptr().as_ref() }.unwrap();
```

**Comment by cakevm** [comment]
Thank you very much! This solution is now working for me. I will proceed with using unsafe for the time being, but I would prefer to eliminate it in the future. If you ever consider changing the trait or have a different approach in mind, please let me know. I would be happy help with the development or create a PR for that.
