### ISSUE TITLE
Infinity loop for calculating with get_output_amount 

### ISSUE THREAD

**Issue by cakevm** [shuhuiluo/uniswap-v3-sdk-rs#93]
I'm encountering an infinite loop when using `pool.get_output_amount(...)`. Unfortunately, I have not been able to find an example to create a test case without relying on custom code. I'm currently working on this in [this branch](https://github.com/cakevm/loom/tree/bench-calc). However, please don't worry too much about it. if you don't have any code to test my case, feel free to close this issue, as I can't confirm whether it's a problem with the library. I just thought better let you know before keeping some bug in the dark.

Find below my test cases:

Block: 20935488

Test1:
Pool: 0x15153da0e9e13cfc167b3d417d3721bf545479bb
From token: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
Input: 2000000000000000000
Result: 2778178708355395 <- working

Test2:
Pool: 0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8
From token: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
Input: 2000000000000000000
Result: / < -infinit loop

**Comment by shuhuiluo** [comment]
@cakevm In your implementation of `next_initialized_tick_within_one_word`, there's some extra stuff.
https://github.com/cakevm/loom/commit/520442920028cbdf6836a5ed9a1b2903b1022c7b#diff-6f3e07d2b2999690577a00d43debaad3fe0d8320c67226676f26764433c98a3bR106-R117
Have you tried removing these?

**Comment by shuhuiluo** [comment]
I was able to find a bug in `next_initialized_tick_within_one_word` for the `lte == false` case. Thank you very much.
